services:
  bundler:
    image: alchemyplatform/rundler:latest
    environment:
      - BUILDER_PRIVATE_KEY=c6cbc5ffad570fdad0544d1b5358a36edeb98d163b6567912ac4754e144d4edb
      - NODE_HTTP=$ETH_RPC_URL
      - ENTRY_POINTS=$ENTRYPOINT
      - MIN_UNSTAKE_DELAY=2
      - RPC_API=eth,debug
      - RUST_LOG=info
    ports: 
      - '3000:3000'
      - '8080:8080'
